// relay.proto — service definition for cas-relay gRPC API.
//
// Worker authentication:  gRPC metadata keys x-worker-id / x-worker-ts / x-worker-sig
// Client authentication:  gRPC metadata key  authorization: bearer <relay_task_token>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/relay.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Relay_WorkerStream_FullMethodName  = "/relay.v1.Relay/WorkerStream"
	Relay_TaskStream_FullMethodName    = "/relay.v1.Relay/TaskStream"
	Relay_UploadPayload_FullMethodName = "/relay.v1.Relay/UploadPayload"
	Relay_CancelTask_FullMethodName    = "/relay.v1.Relay/CancelTask"
)

// RelayClient is the client API for Relay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Relay is the single gRPC service that mediates between workers and clients.
type RelayClient interface {
	// WorkerStream is a bidirectional stream — one per worker connection.
	// Worker sends task output (stdout/stderr/metric/event/status).
	// Relay sends back TypePayload commands when the client uploads encrypted data.
	WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WorkerCommand], error)
	// TaskStream is a server-side stream — one per client × task subscription.
	// The client receives backfilled and live messages for the requested task.
	TaskStream(ctx context.Context, in *TaskStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskMessage], error)
	// UploadPayload delivers the client's encrypted task payload to the worker.
	// Replaces the former HTTP PUT /tasks/{task_id}/payload endpoint.
	UploadPayload(ctx context.Context, in *UploadPayloadRequest, opts ...grpc.CallOption) (*UploadPayloadResponse, error)
	// CancelTask sends a cancel signal to the worker executing the given task.
	// The client must present a valid relay_task_token scoped to that task_id.
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
}

type relayClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClient(cc grpc.ClientConnInterface) RelayClient {
	return &relayClient{cc}
}

func (c *relayClient) WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WorkerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[0], Relay_WorkerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, WorkerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_WorkerStreamClient = grpc.BidiStreamingClient[WorkerMessage, WorkerCommand]

func (c *relayClient) TaskStream(ctx context.Context, in *TaskStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[1], Relay_TaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskStreamRequest, TaskMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_TaskStreamClient = grpc.ServerStreamingClient[TaskMessage]

func (c *relayClient) UploadPayload(ctx context.Context, in *UploadPayloadRequest, opts ...grpc.CallOption) (*UploadPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPayloadResponse)
	err := c.cc.Invoke(ctx, Relay_UploadPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, Relay_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServer is the server API for Relay service.
// All implementations must embed UnimplementedRelayServer
// for forward compatibility.
//
// Relay is the single gRPC service that mediates between workers and clients.
type RelayServer interface {
	// WorkerStream is a bidirectional stream — one per worker connection.
	// Worker sends task output (stdout/stderr/metric/event/status).
	// Relay sends back TypePayload commands when the client uploads encrypted data.
	WorkerStream(grpc.BidiStreamingServer[WorkerMessage, WorkerCommand]) error
	// TaskStream is a server-side stream — one per client × task subscription.
	// The client receives backfilled and live messages for the requested task.
	TaskStream(*TaskStreamRequest, grpc.ServerStreamingServer[TaskMessage]) error
	// UploadPayload delivers the client's encrypted task payload to the worker.
	// Replaces the former HTTP PUT /tasks/{task_id}/payload endpoint.
	UploadPayload(context.Context, *UploadPayloadRequest) (*UploadPayloadResponse, error)
	// CancelTask sends a cancel signal to the worker executing the given task.
	// The client must present a valid relay_task_token scoped to that task_id.
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	mustEmbedUnimplementedRelayServer()
}

// UnimplementedRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServer struct{}

func (UnimplementedRelayServer) WorkerStream(grpc.BidiStreamingServer[WorkerMessage, WorkerCommand]) error {
	return status.Error(codes.Unimplemented, "method WorkerStream not implemented")
}
func (UnimplementedRelayServer) TaskStream(*TaskStreamRequest, grpc.ServerStreamingServer[TaskMessage]) error {
	return status.Error(codes.Unimplemented, "method TaskStream not implemented")
}
func (UnimplementedRelayServer) UploadPayload(context.Context, *UploadPayloadRequest) (*UploadPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPayload not implemented")
}
func (UnimplementedRelayServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedRelayServer) mustEmbedUnimplementedRelayServer() {}
func (UnimplementedRelayServer) testEmbeddedByValue()               {}

// UnsafeRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServer will
// result in compilation errors.
type UnsafeRelayServer interface {
	mustEmbedUnimplementedRelayServer()
}

func RegisterRelayServer(s grpc.ServiceRegistrar, srv RelayServer) {
	// If the following call panics, it indicates UnimplementedRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Relay_ServiceDesc, srv)
}

func _Relay_WorkerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayServer).WorkerStream(&grpc.GenericServerStream[WorkerMessage, WorkerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_WorkerStreamServer = grpc.BidiStreamingServer[WorkerMessage, WorkerCommand]

func _Relay_TaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayServer).TaskStream(m, &grpc.GenericServerStream[TaskStreamRequest, TaskMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_TaskStreamServer = grpc.ServerStreamingServer[TaskMessage]

func _Relay_UploadPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).UploadPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_UploadPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).UploadPayload(ctx, req.(*UploadPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Relay_ServiceDesc is the grpc.ServiceDesc for Relay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Relay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.Relay",
	HandlerType: (*RelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadPayload",
			Handler:    _Relay_UploadPayload_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _Relay_CancelTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerStream",
			Handler:       _Relay_WorkerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TaskStream",
			Handler:       _Relay_TaskStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/relay.proto",
}
