// relay.proto — service definition for cas-relay gRPC API.
//
// Worker authentication:  gRPC metadata keys x-worker-id / x-worker-ts / x-worker-sig
// Client authentication:  gRPC metadata key  authorization: bearer <relay_task_token>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerMessage is a single message sent by a worker to the relay.
// The data field contains raw JSON whose shape depends on type:
//
//	stdout / stderr  →  {"text": "..."}
//	metric           →  MetricData JSON
//	event            →  {"name": "...", ...}   (key_exchange, stream_ended, …)
//	status           →  arbitrary user JSON
type WorkerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "stdout" | "stderr" | "metric" | "event" | "status"
	Ts            float64                `protobuf:"fixed64,3,opt,name=ts,proto3" json:"ts,omitempty"`   // Unix timestamp, fractional seconds
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // raw JSON bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkerMessage) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *WorkerMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WorkerCommand is a message sent by the relay to the worker.
// Currently only carries TypePayload (encrypted task payload from client).
type WorkerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "payload"
	Ts            float64                `protobuf:"fixed64,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // {"enc": "<base64url(nonce + ciphertext)>"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCommand) Reset() {
	*x = WorkerCommand{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCommand) ProtoMessage() {}

func (x *WorkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCommand.ProtoReflect.Descriptor instead.
func (*WorkerCommand) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkerCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkerCommand) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *WorkerCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TaskStreamRequest identifies which task stream the client wants to subscribe to.
type TaskStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamRequest) Reset() {
	*x = TaskStreamRequest{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamRequest) ProtoMessage() {}

func (x *TaskStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamRequest.ProtoReflect.Descriptor instead.
func (*TaskStreamRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStreamRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// TaskMessage is one message delivered to a subscribing client.
// seq is the monotonic per-task counter assigned by TaskStream.Publish.
type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Ts            float64                `protobuf:"fixed64,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // raw JSON bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *TaskMessage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskMessage) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *TaskMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TaskMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadPayloadRequest carries the encrypted task payload from the client.
type UploadPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // JSON: {"enc": "<base64url(nonce + ciphertext)>"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPayloadRequest) Reset() {
	*x = UploadPayloadRequest{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPayloadRequest) ProtoMessage() {}

func (x *UploadPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPayloadRequest.ProtoReflect.Descriptor instead.
func (*UploadPayloadRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPayloadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadPayloadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPayloadResponse) Reset() {
	*x = UploadPayloadResponse{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPayloadResponse) ProtoMessage() {}

func (x *UploadPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPayloadResponse.ProtoReflect.Descriptor instead.
func (*UploadPayloadResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\brelay.v1\"`\n" +
	"\rWorkerMessage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x01R\x02ts\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"`\n" +
	"\rWorkerCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x01R\x02ts\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\",\n" +
	"\x11TaskStreamRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"p\n" +
	"\vTaskMessage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"C\n" +
	"\x14UploadPayloadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x17\n" +
	"\x15UploadPayloadResponse2\xe3\x01\n" +
	"\x05Relay\x12D\n" +
	"\fWorkerStream\x12\x17.relay.v1.WorkerMessage\x1a\x17.relay.v1.WorkerCommand(\x010\x01\x12B\n" +
	"\n" +
	"TaskStream\x12\x1b.relay.v1.TaskStreamRequest\x1a\x15.relay.v1.TaskMessage0\x01\x12P\n" +
	"\rUploadPayload\x12\x1e.relay.v1.UploadPayloadRequest\x1a\x1f.relay.v1.UploadPayloadResponseB\x1cZ\x1acas-relay/internal/relayv1b\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_relay_proto_goTypes = []any{
	(*WorkerMessage)(nil),         // 0: relay.v1.WorkerMessage
	(*WorkerCommand)(nil),         // 1: relay.v1.WorkerCommand
	(*TaskStreamRequest)(nil),     // 2: relay.v1.TaskStreamRequest
	(*TaskMessage)(nil),           // 3: relay.v1.TaskMessage
	(*UploadPayloadRequest)(nil),  // 4: relay.v1.UploadPayloadRequest
	(*UploadPayloadResponse)(nil), // 5: relay.v1.UploadPayloadResponse
}
var file_relay_proto_depIdxs = []int32{
	0, // 0: relay.v1.Relay.WorkerStream:input_type -> relay.v1.WorkerMessage
	2, // 1: relay.v1.Relay.TaskStream:input_type -> relay.v1.TaskStreamRequest
	4, // 2: relay.v1.Relay.UploadPayload:input_type -> relay.v1.UploadPayloadRequest
	1, // 3: relay.v1.Relay.WorkerStream:output_type -> relay.v1.WorkerCommand
	3, // 4: relay.v1.Relay.TaskStream:output_type -> relay.v1.TaskMessage
	5, // 5: relay.v1.Relay.UploadPayload:output_type -> relay.v1.UploadPayloadResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
